Lesson 6
SonaliBedge/react-todo pull request #6
Opened 2024-04-09 00:54 UTC by SonaliBedge

Reusable Components, Imperative React

2024-04-09 19:02 UTC, ElijahMSmith requested changes

2024-04-09 19:02 UTC, ElijahMSmith commented on src/InputWithLabel.jsx
> +import * as React from "react";
I think you should replace `import * as React from "react";` with an explicit import of only the things you need. 

Here, it would be `import { useRef, useEffect } from 'react';`

Two reasons for this:
- Writing `React.useEffect` every time instead of just `useEffect` is verbose, especially when you will start writing components with more and more hooks.
- We generally don't want to import anything more than what we need into code. I'm not an expert in how bundling and imports work in React, but in some cases (including outside of JS/React) importing everything can lead to larger application bundles/files than what you actually need. It probably won't be noticeable here, but it's worth thinking about in the future. JS has to be loaded from somewhere to be used in your site. This either means a bigger single JS file when you `npm run build` or, in more complex cases, downloading JS from the server where your application is hosted.

2024-04-09 20:34 UTC, SonaliBedge commented on src/InputWithLabel.jsx
> +import * as React from "react";
Thank you very much for your valuable suggestions. I have implemented all the changes you recommended. I will resubmit the pull request. In the future, I will ensure to incorporate these adjustments into all of my code.

2024-04-10 03:39 UTC, ElijahMSmith approved these changes

2024-04-10 03:39 UTC, ElijahMSmith commented on src/index.css
> +span:nth-child(2) {
I don't think this is doing what you want it to do. You don't have a span with two children above, so this selector doesn't match anything. If you want space between them, just select the `<a>` or `<button>` directly by giving one of them a class or ID.

2024-04-10 03:39 UTC, ElijahMSmith commented on src/TodoListItem.jsx
>        </span>
We still don't need a span around either this `<a>` tag nor the `<button>` since we aren't using it to apply any styles, so let's remove those too.

2024-04-11 18:00 UTC, merged